theme: jekyll-theme-minimal
title: Bellit CV
description: Desarrollador Full‑Stack especializado en webs profesionales, sistemas multilingües y arquitectura de contenidos. Aquí encontrarás mis proyectos, mi experiencia y la forma en que trabajo. Disponible para colaboraciones y nuevos retos.
